services:
  nginx:
    build:
      context: requirements/nginx
    image:
      nginx_image
    container_name: nginx_container
      #    depends_on:
      #      - wordpress
    ports:
      - 443:443
      #  wordpress:
      #    image:
      #    build:
      #    container_name:
      #    depends_on:
      #    volume:
      #    port:
      #  mariadb:
      #    image:
      #    build:
      #    container_name:
      #    depends_on:
      #    volume:
      #    port:
