services:
  nginx:
    build:
      context: requirements/nginx
    image: nginx
    container_name: nginx_container
    restart: always #unless-stopped
    depends_on:
      wordpress:
        condition: service_completed_successfully
    ports:
      - 443:443
    volumes:
      - wp_volume:/var/www/html/

  wordpress:
    build:
      context: requirements/wordpress
    image: wordpress
    container_name: wordpress_container
    restart: always #unless-stopped
    depends_on:
      mariadb:
        condition: service_completed_successfully
    volumes:
      - wp_volume:/var/www/html/

  mariadb:
    build:
      context: requirements/mariadb
    image: mariadb
      #TODO: container name resolves to IP. hardcoded container name must be fixed.
    container_name: mariadb_container
    restart: always #unless-stopped
    volumes:
      - db_volume:/var/lib/mysql/
    env:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_RANDOM_ROOT_PASSWORD=${DB_RANDOM_ROOT_PASSWORD}

volumes:
  wp_volume:
    type: bind

  db_volume:
    type: bind

network:
  wp-net:
