services:
  nginx:
    build:
      context: requirements/nginx
    image: nginx_image
    container_name: nginx_container
    #restart: on-failure
    depends_on:
      wordpress:
        condition: service_completed_successfully
    ports:
      - 443:443
    volumes:
      - wordpress_volume:/home/wordpress

  wordpress:
    build:
      context: requirements/wordpress
    image: wordpress_image
    container_name: wordpress_container
    #restart: on-failure
    depends_on:
      mariadb:
        condition: service_completed_successfully
    volumes:
      - wordpress_volume:/home/wordpress

  mariadb:
    build:
      context: requirements/mariadb
    image: mariadb_image
    #restart: on-failure
    container_name: mariadb_container
    volumes:
      - db_volume:/home/mariadb/

volumes:
  wordpress_volume:
    external: true

  db_volume:
    external: true
